[project]
name = "rag"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["azure-ai-inference>=1.0.0b9", "dotenv>=0.9.9"]
[tool.pyrefly]
project_includes = ["**/*"]
project_excludes = ["**/.[!/.]*", '**/*venv/**\*']
